KEY_COLOR = 0xff5cf9

SLOT_NONE = 0
SLOT_ARMOR = 1
SLOT_LEFT_HAND = 2
SLOT_RIGHT_HAND = 4

EVENT_MONSTER_DEAD = 1
EVENT_DAMAGE_RECIEVED = 2
EVENT_BOTTLE_USED = 3
EVENT_DAMAGE_GIVEN = 4
EVENT_ITEM_ASSIGNED = 5
EVENT_TRIGGER_RUN = 6

ANIMATION_MOVE_PREFIX = "move"
ANIMATION_MOVE = "move"
ANIMATION_ATTACK = "attack-sword"
ANIMATION_DEATH = "death"

GAME_RUNNING = 0
GAME_PAUSED = 1
GAME_FAILED = 2
GAME_COMPLETED = 3

MENU_NONE = 0
MENU_NEW_GAME = 1
MENU_CONTINUE = 2
MENU_SCORE = 3
MENU_HOTKEYS = 4
