import os

FPS = 30
SIZE = WIDTH, HEIGHT = 1280, 720
TILE_WIDTH = TILE_HEIGHT = 100

DEFAULT_STEP = 7
DEFAULT_LOOT_RANGE = 100
DEFAULT_AI_AGGRESSIVE_RANGE = 200
DEFAULT_AI_LOGIC_MOD = 3

DATA_DIR = "data"
IMAGES_DIR = os.path.join(DATA_DIR, "images")
SOUNDS_DIR = os.path.join(DATA_DIR, "sounds")
LEVEL_DIR = os.path.join(DATA_DIR, "levels")
