@startuml

'Текущее состояние игры. Положение объекто, количество вещей и тд
class State {
}

'Настройки игры
class Config {
}


interface Renderable {
    render()
}

'class Landscape {
'}

class StaticObject {
    bool is_obstacle()
}

class Rock {
}

class Trees {
}

class Meadow {
}

class Inventory {
}

class Item {
}

class Bottle {
}

class HealthBottle {
}

class Treasure {
}

class DynamicObject {
    move(dx, dy)
}

class Hero {
}

class Enemy {
}

class Scene {
}

class Menu {
}

class Weapon {
    bool attack(Enemy)
}

class Sword {
}

'Landscape --|> Renderable]
Treasure --|> Inventory
DynamicObject --|> Inventory
DynamicObject --|> Renderable
StaticObject --|> Renderable
Rock --|> StaticObject
Trees --|> StaticObject
Meadow --|> StaticObject
Treasure --|> StaticObject
Hero --|> DynamicObject
Enemy --|> DynamicObject

Weapon --|> Item
Bottle --|> Item

Sword --|> Weapon
HealthBottle --|> Bottle


Scene "1" o-U- "0..N" Renderable
Inventory "1" o-U- "0..N" Item

@enduml